string1 = "anita laVa la tina"
print("va" in string1)
print("Original",string1)
print("Mayusculas",string1.upper())
print("Minusculas",string1.lower())
print("Capitalize",string1.capitalize())
string2 = "         anita laVa la tina         "
print("Original2",string2)
print("Strip",string2.strip())
print("Replace",string1.replace("a","x"))
longitud = len(string1)
print("Len1",longitud)
longitud = len(string2)
print("Len2",longitud)
string1_mod = string1.replace(" ","")
print(string1_mod)
longitud = len(string1_mod)
print("Len1_mod",longitud)
print("Count",string1.count("a"))
print("Swapcase",string1.swapcase())
print("Starts",string1.startswith("anita"))
print("Ends",string1.endswith("tina"))
print("Title",string1.title())
print("Digit",string1.isdigit())
telefono = "251012456"
print("Digit2",telefono.isdigit())
print("var[-2]",string1[-2])